### ISSUE TITLE
Errors when building/installing ssh==1.7.14

### ISSUE THREAD

**Issue by nvie** [paylogic/pip-accel#2] opened 2013-04-26 14:05 UTC
Installing ssh==1.7.14 leads to this error, when installed with `pip-accel`:

    (pip-accel) Building binary distribution of ssh (1.7.14) ..
    running bdist_dumb
    running build
    running build_py
    installing to build/bdist.macosx-10.8-intel/dumb
    running install
    running install_lib
    running install_egg_info
    running egg_info
    writing requirements to ssh.egg-info/requires.txt
    writing ssh.egg-info/PKG-INFO
    writing top-level names to ssh.egg-info/top_level.txt
    writing dependency_links to ssh.egg-info/dependency_links.txt
    reading manifest file 'ssh.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'ssh.egg-info/SOURCES.txt'
    removing 'build/bdist.macosx-10.8-intel/dumb/Users/nvie/.virtualenvs/foo/lib/python2.7/site-packages/ssh-1.7.14-py2.7.egg-info' (and everything under it)
    Copying ssh.egg-info to build/bdist.macosx-10.8-intel/dumb/Users/nvie/.virtualenvs/foo/lib/python2.7/site-packages/ssh-1.7.14-py2.7.egg-info
    running install_scripts
    Traceback (most recent call last):
      File "setup.py", line 67, in <module>
        **kw
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/bdist_dumb.py", line 123, in run
        owner=self.owner, group=self.group)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 392, in make_archive
        owner=owner, group=group)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/archive_util.py", line 237, in make_archive
        filename = func(base_name, base_dir, **kwargs)
    TypeError: make_tarball() got an unexpected keyword argument 'owner'
    (pip-accel) Failed to build binary distribution!

Installing with `pip` works just fine. Any clues?

**Comment by l0kix2** [comment] 2015-01-12 16:51
So latest paramiko have this annoying hack https://github.com/paramiko/paramiko/blob/master/setup.py#L52 

Pip installs it without complains, so maybe pip-accel somehow should do it? This issue closed, but it can't see workaround or smth.

**Comment by xolox** [comment] 2015-01-12 21:59
@l0kix2: Just got an email notification from your message here. I don't have time to look into this right now but I will definitely forget if I don't follow up on this in some way, so I'll reopen this issue as a reminder to investigate. If things stay quiet for too long then feel free to *bump* this issue to remind me ;-)

**Comment by l0kix2** [comment] 2015-01-13 19:59
Thanks, i really don't know how to handle it for a long time. When i'm trying to install fabric on mac os via pip-accel it installs paramiko, which fails with `TypeError: make_tarball() got an unexpected keyword argument 'owner'`

**Comment by enkeboll** [comment] 2015-09-04 21:49
Bump, happening over here as well with paramiko-1.12.4 on OS X 10.10.5 with Python 2.7.10 as the base.

**Comment by xolox** [comment] 2015-09-05 20:37
Hi @l0kix2 and @enkeboll,

As I explained before in this issue the bug here is not in pip-accel but in the SSH and Paramiko packages: Various versions of both packages (including apparently the master branch of Paramiko :-s) include a Mac OS X specific customization of the `python setup.py bdist_dumb` command as implemented by [distutils](https://docs.python.org/2/library/distutils.html). This customization has become incompatible with newer versions of distutils which is why installation of SSH and Paramiko via pip-accel on Mac OS X is now broken.

However I understand that just pointing out a bug elsewhere doesn't really help you at all :-). Given that I understand what the problem is here and really it shouldn't be that hard to fix it I decided to create a pull request on the Paramiko project to get this fixed, you can find the pull request here: paramiko/paramiko#582.

In the short term, if the version of Paramiko on the master branch satisfies your requirements you can install it as follows:

```sh
pip-accel install https://github.com/xolox/paramiko/archive/fix-bdist-dumb-mac-os-x.zip
```

Let's hope my pull request is merged quickly :-).

**Comment by enkeboll** [comment] 2015-09-06 00:30
Thanks a lot for the update;.

**Comment by xolox** [comment] 2015-09-10 21:38
My pull request was just merged which means the Paramiko master branch is now installable via pip-accel on Mac OS X. Until a proper release is made you should be able to use e.g. this syntax:

```
pip-accel install https://github.com/paramiko/paramiko/archive/master.zip
```

I believe this is the best I can do so I'm going to go ahead and close this issue now. Thanks for the feedback everyone!

**Closed by xolox** 2015-09-10 21:38 UTC
