### ISSUE TITLE
uses old pip

### ISSUE THREAD

**Issue by oppianmatt** [paylogic/pip-accel#50] opened 2015-03-24 09:37 UTC
in the requirements.txt it pins pip to an old version:

```
pip >= 1.4, < 1.5
```

But pip is up to version 6.0.8 https://pypi.python.org/pypi/pip

Any reason it uses an old version of pip?

**Comment by graingert** [comment] 2015-04-01 10:11
This is a duplicate of #22

**Comment by xolox** [comment] 2015-04-01 10:48
Hi Matthew!

I'm working on upgrading to pip 6, I think the upgrade is mostly done (at least the part without binary wheel support). The main thing that I still need to do is *a lot of testing* (which I've already started on). I'll try to publish the branch containing the upgrade this week so other people can play around with it as well (I've already been asked to make the work in progress changes available via personal email).

@Thomas: Thanks for linking #22 and #50 :-).

**Comment by xolox** [comment] 2015-04-04 11:42
Hi again Matthew,

I just released pip-accel 0.23 which is based on pip 6.0.x so I'm closing this issue now. Please try out pip-accel 0.23, it uses the latest available version of pip (at the time of writing) and includes support for installation of wheels. If you encounter any problems feel free to report a new issue in the issue tracker here on GitHub. Thanks for the feedback!

**Closed by xolox** 2015-04-04 11:42 UTC
